// Auto-generated by `pnpm db:generate-types` — do not edit manually.
// Placeholder until Supabase project is initialized.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      pool_agents: {
        Row: {
          id: string;
          container_id: string;
          container_name: string | null;
          status: 'starting' | 'warm' | 'assigned' | 'joining' | 'in_meeting' | 'interviewing' | 'draining' | 'failed';
          host_port: number | null;
          internal_ip: string | null;
          session_id: string | null;
          error_message: string | null;
          started_at: string;
          assigned_at: string | null;
          last_health_check: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          container_id: string;
          container_name?: string | null;
          status?: 'starting' | 'warm' | 'assigned' | 'joining' | 'in_meeting' | 'interviewing' | 'draining' | 'failed';
          host_port?: number | null;
          internal_ip?: string | null;
          session_id?: string | null;
          error_message?: string | null;
          started_at?: string;
          assigned_at?: string | null;
          last_health_check?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          container_id?: string;
          container_name?: string | null;
          status?: 'starting' | 'warm' | 'assigned' | 'joining' | 'in_meeting' | 'interviewing' | 'draining' | 'failed';
          host_port?: number | null;
          internal_ip?: string | null;
          session_id?: string | null;
          error_message?: string | null;
          started_at?: string;
          assigned_at?: string | null;
          last_health_check?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'fk_pool_agent_session';
            columns: ['session_id'];
            isOneToOne: false;
            referencedRelation: 'voice_sessions';
            referencedColumns: ['id'];
          },
        ];
      };
      voice_sessions: {
        Row: {
          id: string;
          pool_agent_id: string | null;
          status:
            | 'pending'
            | 'connecting'
            | 'active'
            | 'completed'
            | 'failed'
            | 'cancelled';
          meeting_url: string;
          interview_config: Json;
          stakeholder_name: string | null;
          stakeholder_role: string | null;
          callback_url: string | null;
          callback_status: string;
          started_at: string | null;
          ended_at: string | null;
          duration_seconds: number | null;
          results: Json | null;
          pipecat_logs: string | null;
          latency_data: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          pool_agent_id?: string | null;
          status?:
            | 'pending'
            | 'connecting'
            | 'active'
            | 'completed'
            | 'failed'
            | 'cancelled';
          meeting_url: string;
          interview_config: Json;
          stakeholder_name?: string | null;
          stakeholder_role?: string | null;
          callback_url?: string | null;
          callback_status?: string;
          started_at?: string | null;
          ended_at?: string | null;
          duration_seconds?: number | null;
          results?: Json | null;
          pipecat_logs?: string | null;
          latency_data?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          pool_agent_id?: string | null;
          status?:
            | 'pending'
            | 'connecting'
            | 'active'
            | 'completed'
            | 'failed'
            | 'cancelled';
          meeting_url?: string;
          interview_config?: Json;
          stakeholder_name?: string | null;
          stakeholder_role?: string | null;
          callback_url?: string | null;
          callback_status?: string;
          started_at?: string | null;
          ended_at?: string | null;
          duration_seconds?: number | null;
          results?: Json | null;
          pipecat_logs?: string | null;
          latency_data?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'voice_sessions_pool_agent_id_fkey';
            columns: ['pool_agent_id'];
            isOneToOne: false;
            referencedRelation: 'pool_agents';
            referencedColumns: ['id'];
          },
        ];
      };
      session_events: {
        Row: {
          id: string;
          session_id: string;
          event_type: string;
          event_data: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          session_id: string;
          event_type: string;
          event_data?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          session_id?: string;
          event_type?: string;
          event_data?: Json;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'session_events_session_id_fkey';
            columns: ['session_id'];
            isOneToOne: false;
            referencedRelation: 'voice_sessions';
            referencedColumns: ['id'];
          },
        ];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
